title: JSPerf
description: JavaScript Performance Benchmarks
logo: /logo.png

collections:
  benchmarks:
    permalink: /:path
    output: true

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: benchmarks
    values:
      layout: benchmark

contents:
  benchmarks:
    path: '_benchmarks/:slug.md'
    template: '_templates/benchmark.liquid'
    commit: false

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
